
development:
  adapter: postgresql
  encoding: unicode
  database: workforce_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: workforce_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: workforce_production
  pool: 5
